import {
  Navbar,
  NavbarSmall,
  Search,
  CourseNav,
  NavBtn,
  UnitNav,
  NavBgBtn,
  Accordion,
  AccordionItem,
  AccordionSmall,
  AdminSideBar,
  FormNavigation,
} from "./Navigation";
import { Button, LoadingBtn, LogoutButton } from "./Buttons";
import {
  ChapterCard,
  CourseCard,
  HomePageCard,
  TeamCard,
  TutorCard,
  UnitsCard,
} from "./Cards";

import { BarChart, LineChart, PieChart } from "./Charts";

import {
  TutorCardHome,
  TutorSideBar,
  Modal,
  ReturnBackBtn,
  MyEditor,
  ProgressBar,
  AlertBox,
  RequireAuth,
} from "./General";
import {
  StudentRegistrationForm,
  TutorRegistrationForm,
  AdminRegistrationForm,
  LogInForm,
  CourseForm,
  ChapterForm,
  LessonForm,
  UnitForm,
  ResourceForm,
} from "./Forms";

import {
  CommentsSection,
  ResourcesSection,
  CoursesSection,
  ContentSection,
  CourseHeading,
  TeamSection,
  HeroSection,
  Footer,
  UnitsOutline,
} from "./Sections";
import {
  QuillEditor,
  ReactPdfModal,
  S3Uploader,
  AudioPlayer,
  ReactPdf,
  VideoComponent,
  VideoJsPlayer,
} from "./MediaHandlers";
import { VideoEmptyPoster } from "./Skeletons";

import {
  AdminButton,
  AdminCard,
  PaymentsTable,
  StudentsTable,
  NavigateBtn,
  StatusPill,
  CTAButton,
  UsersDataTable,
  StudentsAdminTable,
  CourseAdminCard,
  PageTitle,
  UnitsAdminTable,
  CTAUnitButtonAdmin,
  AdminNavItem,
  AdminSectionTable,
  UsersTableAlternative,
  UsersCard,
} from "./AdminPage";

export {
  LogInForm,
  HomePageCard,
  CourseCard,
  CourseHeading,
  VideoComponent,
  AdminSideBar,
  FormNavigation,
  ChapterCard,
  TutorCard,
  UnitsCard,
  UnitNav,
  QuillEditor,
  TutorSideBar,
  TutorCardHome,
  Footer,
  CourseForm,
  ResourceForm,
  ChapterForm,
  LessonForm,
  UnitForm,
  AlertBox,
  AdminButton,
  AdminCard,
  PaymentsTable,
  StudentsTable,
  NavigateBtn,
  StatusPill,
  UsersDataTable,
  CTAButton,
  StudentsAdminTable,
  PageTitle,
  Button,
  UnitsAdminTable,
  CourseAdminCard,
  CTAUnitButtonAdmin,
  AdminNavItem,
  RequireAuth,
  StudentRegistrationForm,
  TutorRegistrationForm,
  Accordion,
  AccordionSmall,
  AccordionItem,
  AdminSectionTable,
  AdminRegistrationForm,
  UsersTableAlternative,
  ContentSection,
  AudioPlayer,
  VideoEmptyPoster,
  CoursesSection,
  TeamSection,
  HeroSection,
  CommentsSection,
  ResourcesSection,
  ReactPdfModal,
  ReturnBackBtn,
  LogoutButton,
  LoadingBtn,
  Navbar,
  Search,
  CourseNav,
  NavbarSmall,
  NavBtn,
  NavBgBtn,
  Modal,
  TeamCard,
  MyEditor,
  ProgressBar,
  ReactPdf,
  S3Uploader,
  VideoJsPlayer,
  PieChart,
  BarChart,
  LineChart,
  UsersCard,
  UnitsOutline,
};
